Game items
DavidRisch/crossing_consoles pull request #133
Opened 2021-04-08 20:40 UTC by Martina-Scheffler

closes #102

2021-04-09 12:09 UTC, DavidRisch requested changes

2021-04-09 12:09 UTC, DavidRisch commented on src/game/world/items/ItemGenerator.h
> +  class NoItemSpaceException : public std::exception {
Since this Exception is never thrown it should not exist, otherwise its existant would imply that `GenerateItem()` can dealt with a full world (which it currently cant).

2021-04-09 12:09 UTC, DavidRisch commented on src/game/world/items/Points.cpp
> +  point_sprite.AppendString(L"10");
`10` is a magic number also used in ItemGenerator.GenerateItem(). Please find some way of only using it once.

2021-04-09 12:09 UTC, DavidRisch commented on src/game/world/items/Points.h
> + * \brief Items which increases a `Player`s score.
Why is `Items` plural?

2021-04-11 20:13 UTC, Martina-Scheffler commented on src/game/GameLogic.cpp
> +    case ItemType::HEART:
If I do not mention POINTS and HEART here, I get the following error: `error: enumeration value '...' not handled in switch`

2021-04-12 15:45 UTC, merged