Game renderer
DavidRisch/crossing_consoles pull request #81
Opened 2021-03-18 19:04 UTC by julian-fuchs

2021-03-22 10:41 UTC, DavidRisch requested changes

2021-03-22 10:41 UTC, DavidRisch commented on src/game/visual/Renderer.cpp
> +  ColoredCharMatrix rendered_world(viewport_size * block_size + composited_viewport_overhang);
What is the meaning of `composited_viewport_overhang` and why is the renderer using something that looks like it is part of the compositor?

2021-03-22 10:41 UTC, DavidRisch commented on tests/position.cpp
> +  ASSERT_FALSE(position_3 < position_2);
I would argue that `(20, -10)` < `(20, 5)` is true. Otherwise the pair would be nigher smaller, greater nor equal.

2021-03-22 10:41 UTC, DavidRisch commented on tests/game_networking.cpp
> +  bool empty = true;
Please turn this repeated block of code into a function `ExpectTerminalNotEmpty`

2021-03-22 10:41 UTC, DavidRisch commented on tests/colored_string_matrix.cpp
> +  EXPECT_EQ(matrix[0][4], ColoredChar(L'd', WHITE, BLACK));
Add expects to make sure the rest of the matrix did not change. Applies to all/most test here

2021-03-22 10:41 UTC, DavidRisch commented on src/game/visual/Renderer.cpp
>            for (int y = 0; y < block_size.y; y++) {
Instead of this loop construct it would be neater if ColoredCharMatrix had a method to insert a sprite.
Somehat related to that, it looks like ColoredCharMatrix has all of the features of Sprite: Maybe Sprites could be replaced with ColoredCharMatrixes and method to insert a ColoredCharMatrix into a ColoredCharMatrix could be added (which could also be used by the compositor).

2021-03-22 12:00 UTC, julian-fuchs commented on tests/position.cpp
> +  ASSERT_FALSE(position_3 < position_2);
The relational operators are based on the following concept:
![relational_operators](https://user-images.githubusercontent.com/63347930/111986475-49ddae80-8b0e-11eb-914e-80170dfc6c98.png)

2021-03-22 12:47 UTC, DavidRisch commented on tests/position.cpp
> +  ASSERT_FALSE(position_3 < position_2);
How can the pair be 'LessOrEqual' without being equal or less? In other words I think the invariant `(a <= b) == (a < b || a==b)`should hold, but does not currently.

2021-03-22 13:27 UTC, julian-fuchs commented on tests/position.cpp
> +  ASSERT_FALSE(position_3 < position_2);
In fact, there is an error in the above figure - LessOrEqual should also contain Less.

The current implementation follows this concept:
a == b, if a.x == b.x and a.y == b.y (for all operators, e. g. a <= b, if a.x <= b.x and a.y <= b.y)

I think it is not necessary for the implementation to fulfill the invariant as the objects have 2 dimensions instead of just 1.
The invariant (a <= b) == !(a > b) does not hold either.

2021-03-22 16:51 UTC, DavidRisch commented on tests/position.cpp
> +  ASSERT_FALSE(position_3 < position_2);
Accoring to https://en.cppreference.com/w/cpp/language/operator_comparison:
> A common requirement for user-defined operator< is strict weak ordering.

The current implementation violates the [Transitivity of incomparability](https://en.wikipedia.org/wiki/Weak_ordering#Strict_weak_orderings) requirment, example:
x: 5 8	
y: 2 9
z: 4 6

An operator like this would work: https://en.cppreference.com/w/cpp/utility/pair/operator_cmp

The best solution might be to create methods to perform the comparisions needed for the game code, they could have names adaqatly describing the kind of comparision. THis would avoid the expectations assotiated with overloading operators.

2021-03-28 19:23 UTC, DavidRisch approved these changes

2021-03-28 20:26 UTC, merged